# benchmarl/conf/task/vmas/target_defense.yaml
max_steps: 250
num_defenders: 1
num_attackers: 1
sensing_radius: 0.15
attacker_sensing_radius: 0.15
speed_ratio: 0.1
defender_step_size: 0.02
target_distance: 0.05
randomize_attacker_x: true
num_spawn_positions: 8
spawn_area_mode: true
spawn_area_width: 0.2
absolute_observations: true
enable_wall_constraints: false
wall_epsilon: 0.03
fixed_attacker_policy: true
use_apollonius: true
