defaults:
  - submitit_slurm
  - _self_

submitit_folder: ${hydra.sweep.dir}/.submitit/%j
 # maximum time for the job in minutes
timeout_min: 700
cpus_per_task: 32
gpus_per_node: 1
tasks_per_node: 1
mem_gb: null
nodes: 1
name: ${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
partition: ampere
qos: null
comment: null
constraint: null
exclude: null
gres: null
cpus_per_gpu: null
gpus_per_task: null
mem_per_gpu: null
mem_per_cpu: null
account: PROROK-SL3-GPU
signal_delay_s: 120
max_num_timeout: 0
additional_parameters:
  mail-user: "mb2389@cam.ac.uk"
  mail-type: "BEGIN"
array_parallelism: 256
setup:
  - ". /etc/profile.d/modules.sh"
  - "module purge"
  - "module load rhel8/default-amp"
  - "source .bashrc"
  - "module unload cuda/8.0"
  - "module load cuda/12.1 cudnn/8.9_cuda-12.1"
