# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions


name: lint

on:
  push:
    branches: [ $default-branch , "main" ]
  pull_request:
    branches: [ $default-branch , "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Lint
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
        
        set +e
        pre-commit run --all-files
        
        if [ $? -ne 0 ]; then
          git --no-pager diff
          exit 1
        fi
        
       
